### ISSUE TITLE
Testnet v1 Release Checklist

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/espresso#125]
- [ ]  No dependencies on internal repositories
- [ ]  All tests pass
- [ ]  Check all README.md are up to date
- [ ]  README has instructions on how to set up development environment
  - [ ] EsQS
  - [ ] Validator
  - [ ] Wallet
  - [ ] Faucet
- [ ]  README has instructions on how to run tests
- [ ]  Instructions for obtaining help are included in all reasonable starting points, e.g. all the README.md files
- [ ]  All repos have appropriate license
- [ ]  Check automatically that all files have the appropriate license
- [ ] Integration tests corresponding to a script to be agreed on with product
- [ ]  All text and visuals have been proofread
- [ ]  No alarming code comments
- [ ]  All TODO comments are clear, actionable, and linked to a GitHub issue
- [ ]  Most if not all documentation is available by following a URL without the user needing to first install tools, build the documentation, and run a web server
   - [ ] Wallet
   - [ ] Validator
- [ ]  Calls to sleep, unwrap, exit, panic and other functions that can mask fragile behavior have been reviewed
- [ ]  Github issue template
- [ ]  Github PR template
- [ ]  Contributing guideline (often CONTRIBUTING.md)
- [ ]  Code of conduct
- [ ]  Contributor License Agreement (CLA)
- [ ]  All services have status checks that are being monitored
- [ ]  Alerts are configured so the right people will be alerted, but only when really necessary
- [ ]  We can inspect what exact version (git revision) of each service is running (for example by calling an endpoint).
