### ISSUE TITLE
Testnet v1 Staging Checklist

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/espresso#132]
At the time of staging deployment, we should check off anything in the release checklist that is unlikely to change between staging and release and that doesn't relate directly to releasing code publicly (e.g. open sourcing related tasks are not included here).
- [x]  All tests pass
- [x]  Check all README.md are up to date
- [x]  README has instructions on how to set up development environment
  - [x] EsQS
  - [x] Validator
  - [x] Wallet
  - [x] Faucet
- [x]  README has instructions on how to run tests
- [ ]  ~Instructions for obtaining help are included in all reasonable starting points, e.g. all the README.md files~ (not relevant for staging as we will not have any users, no support channels to point to)
- [ ]  All TODO comments are clear, actionable, and linked to a GitHub issue (see below)
- [x]  All services have status checks that are being monitored
- [x]  Alerts are configured so the right people will be alerted, but only when really necessary (#364)
- [x]  We can inspect what exact version (git revision) of each service is running (#121).
